title: "Akos Kokai"
permalink: /posts/:year/:month/:day/:title/
show_drafts: false
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "main"
      show_title: false
  - 
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
